"""Added filename

Revision ID: 049626cf2620
Revises: 5012d11e936c
Create Date: 2019-08-23 15:38:54.809328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049626cf2620'
down_revision = '5012d11e936c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_item', sa.Column('filename', sa.Text(), nullable=True))
    op.add_column('todo_item', sa.Column('mimetype', sa.Text(), nullable=True))
    op.add_column('todo_item', sa.Column('unique_filename', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_item', 'unique_filename')
    op.drop_column('todo_item', 'mimetype')
    op.drop_column('todo_item', 'filename')
    # ### end Alembic commands ###
