"""Updated User table

Revision ID: 090127e075f5
Revises: 018785bd6dba
Create Date: 2019-08-13 17:54:10.566545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090127e075f5'
down_revision = '018785bd6dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_username'), 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_username'), 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
